#!/bin/sh

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source $CONFIG_DIR/colors.sh
source $CONFIG_DIR/icons.sh
source $CONFIG_DIR/settings.sh

bar=( 
    color=0x0000000
    border_color=0x0000000
    border_width=1
    position=top
    height=38
    margin=-15
    # padding_left=18 
    # padding_right=10 
    notch_display_height=0
    notch_width=200
    notch_offset=0
    corner_radius=0
    blur_radius=36
    shadow=on
    sticky=on
    topmost=off
    display=all
    hidden=off
    font_smoothing=off
)
sketchybar --bar "${bar[@]}"


sketchybar --default \
    background.height=28 \
    background.corner_radius=0 \
    background.padding_right=0 \
    background.color=$ITEM_BG \
    icon.font="$FONT_ICON:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_LABEL:Medium:12.0" \
    label.color=0xffffffff \
    label.y_offset=0 \
    label.padding_left=5 \
    label.padding_right=5 \
    popup.background.color=0xee1c1c1e \
	popup.background.border_color=0xffcccccc \
	popup.background.border_width=1 \
	popup.background.corner_radius=16 \
	popup.height=34

# Adjust bar on startup
source "$PLUGIN_DIR/adjust_bar.sh"

# LEFT
source "$ITEMS_DIR/apple.sh"
source "$ITEMS_DIR/aerospace.sh"
source "$ITEMS_DIR/front_app.sh"

# CENTER

# RIGHT
source "$ITEMS_DIR/calendar.sh"
source "$ITEMS_DIR/battery.sh"
source "$ITEMS_DIR/network.sh"
source "$ITEMS_DIR/status.sh"
source "$ITEMS_DIR/spotify.sh"



##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
